[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "_ts-team_"
name = "BepInExModTemplate"
description = "TODO: Fill in short mod description."
websiteUrl = "" # TODO: Add a link to your mod repository here (optional)
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2403"

[build]
icon = "../../icon.png"
readme = "../../README.md"
outdir = "../../artifacts/thunderstore/"

[[build.copy]]
source = "../../artifacts/bin/BepInExModTemplate/release/_Guid_.dll"
target = "BepInEx/plugins/_ts-team_-BepInExModTemplate/"

[[build.copy]]
source = "../../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../../LICENSE"
target = "/"

# The following config options only apply when using TCLI to publish to Thunderstore directly:

[publish]
# See communities at:
# https://thunderstore.io/api/experimental/community/
communities = [ "CloverPit", ]

[publish.categories]
# See categories at:
# https://thunderstore.io/api/experimental/community/CloverPit/category/
CloverPit = [ "mods", ]
